### ISSUE TITLE
New opam release ?

### ISSUE THREAD

**Issue by LaurentMazare** [zshipko/ocaml-py#11]
Hi Zach,
Would you mind crafting a new opam release with the latest ocaml-py version ?
I'm asking as I started using ocaml-py in a new project ([ocaml-gym](https://github.com/LaurentMazare/ocaml-gym)) relying on the newly added numpy/bigarray bridge, and would like to use the dependency in opam too.
Happy to help with this if there is anything I can do.

**Comment by zshipko** [comment]
Sure, I will make a new release ASAP! Most likely this evening or tomorrow morning, but I will let you know.

**Comment by zshipko** [comment]
Alright, a PR for the new release has been made: https://github.com/ocaml/opam-repository/pull/13335

**Comment by LaurentMazare** [comment]
Thanks!
There seems to be some test failures in the opam CI due to me introducing a call to `Sys.getenv_opt` which was only introduced in 4.05.
I'm not sure how much you want to keep the compatibility with 4.03 and 4.04 but if you care about them you should probably replace `Sys.getenv_opt` with a `Sys.getenv` wrapped into some `try` `with` block (I can do a PR for this if this helps).

**Comment by LaurentMazare** [comment]
I think I'm all good to go if #14 looks good to you. Feature wise it should cover most of my needs (maybe some additional helper library could be interesting but nothing that I plan on working on urgently).

**Comment by zshipko** [comment]
Great! Python modules in OCaml has been something I wanted to add for a while - glad you were able to do it.

Here is the new opam PR: https://github.com/ocaml/opam-repository/pull/13340

**Comment by LaurentMazare** [comment]
Looks like this has been merged now, thanks!
