### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by nilsbecker** [zshipko/ocaml-py#2]
hi, i just tried to install on os x 10.12. opam installation seems to succeed. 
i have python installed via anaconda. i activate my python 3.6 environment in a shell so that `python` will call a 3.6 python executable. i then start utop and `#require "py";;` but get 
`Exception: Init.Python_not_found.`

**Comment by nilsbecker** [comment]
i guess i need to tell `Py` where to find python libraries -- what is the way to do that? it would be good to document this in the README as well...

**Comment by zshipko** [comment]
Hey @nilsbecker,

Sorry I didn't make that more clear -- you can point to the Python shared library path using the `OCAML_PY_VERSION` environment variable. 

I will be sure to add this to the README file.

**Comment by nilsbecker** [comment]
ok, is there a simple python command line that spits out the necessary path? i.e. if i have a working interpreter, how can i easily get the corresponding lib path?

**Comment by nilsbecker** [comment]
one SO answer suggests: `import inspect, os; os.dirname(inspect.getfile(inspect))`

**Comment by zshipko** [comment]
@nilsbecker, I'm not sure of a simple way to do that.

However, this worked for me.

```bash
 find `python3 -c "import inspect, os; print(os.path.dirname(inspect.getfile(inspect)))"` -name 'libpython*.so'`
```

**Comment by nilsbecker** [comment]
hmm that command finds nothing for me, and 
```
find `python -c "import inspect, os; print(os.path.dirname(inspect.getfile(inspect)))"` -name libpython*
```
finds `libpython3.6m.a` and some things within cython.

so the env variable needs the shared library file, yes? the naming of the variable to me suggests that it expects something like '3.6' i.e. a version number.

**Comment by zshipko** [comment]
Yeah, it should point to the shared library file. I agree that the name could be improved but I don't want to change it at this point. 

I don't have much experience using Anaconda, but is it possible that it doesn't include the shared library file?

**Comment by nilsbecker** [comment]
hmm i don't think that's likely. could it have a different name on os x? but `libpython*.dylib` gives nothing as well...

**Comment by nilsbecker** [comment]
ok so i can find the following file: `<anaconda-root>/envs/py3/lib/libpython3.6m.dylib` which is actually not in a subdir of the directory found with inspect above, but forks one directory above... so it's found with 
```
find `python -c "import inspect, os; print(os.path.dirname(inspect.getfile(inspect)))"`/.. -name libpython*.dylib
```

**Comment by nilsbecker** [comment]
this seems cumbersome?

**Comment by zshipko** [comment]
Hmm, what about just

```bash
find $ANACONDA_PATH -name 'libpython*.dylib'
```

I just installed anaconda and it gave me the following output after running that:

```
/home/zach/anaconda3/pkgs/python-3.6.4-hc3d631a_1/lib/libpython3.6m.so
/home/zach/anaconda3/lib/libpython3.6m.so
```

It seems that `~/anaconda3/lib` contains the library needed.

**Comment by nilsbecker** [comment]
in my case it's a bit more involved since my python3 is in an environment created within the anaconda distribution. that's why it is below an `envs/py3/` directory which serves as the root for that particular python subinstallation. anyway, `$ANACONDA_PATH` is not defined for me.. for now i know where to find what i need though, thanks!

**Comment by zshipko** [comment]
Agh, okay that makes sense. Maybe Anaconda can tell you where the shared libraries are installed for the current env. I will look into it when I get some time.

**Comment by zshipko** [comment]
Using anaconda/virtualenv should work as of the latest commit. Let me know if there are any further issues.
