### ISSUE TITLE
Calling method from Python Class

### ISSUE THREAD

**Issue by gabrik** [zshipko/ocaml-py#3]
Hi,

I just start playing with your module, I need to call a method from a python class that take only self as argument, I have tried with:
`let pls = Py.run (Py.Object.get_attr_s l "get_plugins") [Py.List []] `
I got: 
`Fatal error: exception Py.Python_error("get_plugins() takes 1 positional argument but 2 were given")`

Also tried to use directly Object.call 

`  let pls = Py.Object.call (Py.Object.get_attr_s l "get_plugins") in`

But I got:
`Fatal error: exception Py.Python_error("argument should be string, bytes or integer, not list")`

There is a way to do that?

Thanks

**Comment by zshipko** [comment]
Hey, it seems like maybe your first try will work if you remove the inner `Py.List []` from the arguments.

Like this:

```
let pls = Py.run (Py.Object.get_attr_s l "get_plugins") []
```

You can also use the `$.` operator to get an attribute and `$` to call an object the following is also equivalent:

```
let pls = Py.(l $. String "get_plugins" $ [])
```

Let me know if that works for you.

**Comment by gabrik** [comment]
Hi, thanks for the fast response

I had a try but I got:
`Fatal error: exception Py.Python_error("argument should be string, bytes or integer, not list")`

To help understand I also post the OCaml code (which is pretty little)

```
open Core
open Printf

let () =
  let mpl = Py.PyModule.import "PluginLoader" in
  let pl = Py.Object.get_attr_s mpl "PluginLoader" in
  let l = Py.run pl [Py.List [Py.String "/home/ubuntu/app/plugins"]] in
  let pls = Py.run (Py.Object.get_attr_s l "get_plugins") [] in
  let pls_l = Py.Object.to_list Py.Object.to_string pls in
  ignore @@ List.map pls_l ~f:(fun e -> printf "%s\n" e)
```
The PluginLoader is a class that I use for load plugins,
In python I use this class in this way
```
import PluginLoader
pl = PluginLoader('/some/path/to/plugins')
plugins = pl.get_plugins()
```
I'm using you Py module wrong?

**Comment by zshipko** [comment]
When calling arguments, you do not need to wrap the values in a list. Do you still get the error if you change the following line:

```
 let l = Py.run pl [Py.List [Py.String "/home/ubuntu/app/plugins"]] in
```

to 

```
let l = Py.run pl [Py.String "/home/ubuntu/app/plugins"] in
```

I wonder if `PluginLoader` does something special with the arguments? I made a stub version of the `PluginLoader` module to test your code on an it seemed to work correctly using the code you posted above, even without the change I suggested. Is there any chance you can post the relevant parts of `PluginLoader.py`

Here is my `PluginLoader.py` stub code:

```
class PluginLoader:
    def __init__(self, s):
        self.s = s

    def get_plugins(self):
         return ["a", "b", "c"]
```

**Comment by gabrik** [comment]
This is pretty strange, here is my class:
```
class PluginLoader(object):

    def __init__(self, plugin_path):
        self.PluginFolder = plugin_path
        self.MainModule = "__init__"
        self.plugins = []
    
    def get_plugins(self):
        self.plugins = []
        possible_plugins = os.listdir(self.PluginFolder)
        for p in possible_plugins:
            location = os.path.join(self.PluginFolder, p)
            if not os.path.isdir(location) or not '{}.py'.format(self.MainModule) in os.listdir(location):
                continue

            info = os.path.join(location, '{}.py'.format(self.MainModule))
            self.plugins.append({"name": p, "info": info})
            sys.path.append(os.path.join(sys.path[0], self.PluginFolder, p))
        return self.plugins

    def load_plugin(self, name):

        module = importlib.machinery.SourceFileLoader(name['name'], name['info']).load_module()
        sys.path.append(os.path.abspath(name['info']))
        return module

    def locate_plugin(self, name):
        located = [x for x in self.plugins if x["name"] == name]
        if len(located) > 0:
            return located[0]
        return None

    def install_requirements(self, requirements):
        pip_args = ['install']
        for r in requirements:
            pip_args.append(r)

        pip.main(pip_args)
```
It should retuns a list of dictionaries maybe the problem in in another part of my code.

**Comment by zshipko** [comment]
Okay, if you change this line in your OCaml code: 

```
let l = Py.run pl [Py.List [Py.String "/home/ubuntu/app/plugins"]] in
```
to 
```
let l = Py.run pl [Py.String "/home/ubuntu/app/plugins"] in
```

then it should work. That got rid of the errors for me.

**Comment by zshipko** [comment]
Yes, that's correct. Glad it's working now!
